name: Run RSI Calculation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools
        pip install numpy==1.24.2  # A more recent numpy version
        pip install yfinance pandas pandas_ta beautifulsoup4 requests

    - name: Run RSI calculation script
      run: |
        python rsi_script.py








